import os
os.makedirs("data", exist_ok=True)

schemes = [
("pm_krishi_sinchai", "PM Krishi Sinchai Yojana Irrigation Subsidy\nCategory: Farmer\nBenefit: Irrigation subsidy up to 55 percent for small farmers\nEligibility: All farmers with agricultural land\nHow to Apply: Contact local agriculture department or Krishi Vigyan Kendra\nDocuments: Aadhar card, land documents, bank account\nHelpline: 1800-180-1551\nWebsite: pmksy.gov.in\nFeatures: Drip irrigation subsidy, sprinkler system subsidy, water conservation, Har Khet Ko Pani, More Crop Per Drop"),
("soil_health_card", "Soil Health Card Scheme Free Soil Testing\nCategory: Farmer\nBenefit: Free soil testing and crop recommendation card every 3 years\nEligibility: All farmers across India\nHow to Apply: Visit nearest Krishi Vigyan Kendra or agriculture office\nDocuments: Aadhar card, land documents\nHelpline: 1800-180-1551\nFeatures: Free soil nutrient analysis, fertilizer recommendations, reduces input costs, card valid 3 years"),
("enam", "eNAM Electronic National Agriculture Market Online Crop Selling\nCategory: Farmer\nBenefit: Online platform to sell crops at better prices across India\nEligibility: All registered farmers\nHow to Apply: Register at enam.gov.in or through local APMC\nDocuments: Aadhar card, bank account, land records\nHelpline: 1800-270-0224\nFeatures: Online crop selling, better price discovery, transparent bidding, direct bank payment, reduces middlemen"),
("pm_kisan_maandhan", "PM Kisan Maandhan Yojana Farmer Pension Rs 3000 Monthly\nCategory: Farmer Pension\nBenefit: Rs 3000 per month pension after age 60\nEligibility: Small and marginal farmers aged 18 to 40 years\nHow to Apply: Visit nearest Common Service Centre CSC\nDocuments: Aadhar card, bank account, land records\nHelpline: 1800-267-6888\nFeatures: Minimum pension Rs 3000 per month, government matches contribution, family pension on death of farmer"),
("kisan_vikas_patra", "Kisan Vikas Patra Investment Scheme Money Doubles\nCategory: Farmer Investment\nBenefit: Money doubles in 115 months at 7.5 percent interest\nEligibility: Any Indian citizen above 18 years\nHow to Apply: Post office or authorized banks\nDocuments: Aadhar card, PAN card\nHelpline: 1800-11-2011\nFeatures: Safe government investment, available Rs 1000 to 50000 denominations, premature withdrawal after 2.5 years allowed"),
("paramparagat_krishi", "Paramparagat Krishi Vikas Yojana Organic Farming Support\nCategory: Farmer\nBenefit: Rs 50000 per hectare over 3 years for organic farming\nEligibility: Farmers willing to adopt organic farming in clusters of 50\nHow to Apply: Contact agriculture department form cluster of 50 farmers\nDocuments: Aadhar card, land documents, bank account\nHelpline: 1800-180-1551\nFeatures: Organic farming promotion, cluster approach, training and certification, marketing support for organic produce"),
("pm_surakshit_matritva", "PM Surakshit Matritva Abhiyan Free Antenatal Checkup\nCategory: Health Women\nBenefit: Free antenatal check-up on 9th of every month at government hospital\nEligibility: All pregnant women in second and third trimester\nHow to Apply: Visit nearest government health center on 9th of every month\nDocuments: Aadhar card, pregnancy card\nHelpline: 104\nFeatures: Free ultrasound blood tests doctor consultation, high-risk pregnancy identification, available at PHC CHC district hospitals"),
("janani_suraksha", "Janani Suraksha Yojana Safe Delivery Cash Incentive\nCategory: Health Women\nBenefit: Rs 1400 cash for delivery in government hospital rural Rs 1000 urban\nEligibility: BPL pregnant women SC ST women for all deliveries\nHow to Apply: Register at nearest ASHA worker or government hospital\nDocuments: Aadhar card, BPL card, bank account\nHelpline: 104\nFeatures: Cash incentive for institutional delivery, ASHA worker gets Rs 600, free delivery and post-delivery care, reduces maternal mortality"),
("jan_aushadhi", "Pradhan Mantri Bhartiya Janaushadhi Generic Cheap Medicines\nCategory: Health\nBenefit: Generic medicines at 50 to 90 percent cheaper than branded medicines\nEligibility: All citizens of India\nHow to Apply: Visit nearest Janaushadhi Kendra over 9000 centers across India\nDocuments: Doctor prescription\nHelpline: 1800-111-255\nWebsite: janaushadhi.gov.in\nFeatures: Over 1900 medicines available, saves Rs 2000 to 3000 per year per family, quality assured medicines"),
("poshan_abhiyaan", "Poshan Abhiyaan National Nutrition Mission Child Nutrition\nCategory: Health Women Child\nBenefit: Free nutritional support for pregnant women and children under 6 years\nEligibility: Pregnant women, new mothers, children under 6 years\nHow to Apply: Register at nearest Anganwadi center\nDocuments: Aadhar card, birth certificate of child\nHelpline: 1800-11-8004\nFeatures: Free nutritional food supplements, growth monitoring, counseling, reduces stunting and wasting in children"),
("rashtriya_bal_swasthya", "Rashtriya Bal Swasthya Karyakram Child Health Screening Free\nCategory: Health Child\nBenefit: Free health screening and treatment for children aged 0 to 18 years\nEligibility: All children from birth to 18 years\nHow to Apply: School health checkup or Anganwadi center mobile teams visit schools\nDocuments: Birth certificate, Aadhar card\nHelpline: 104\nFeatures: 4D screening Defects Deficiencies Diseases Developmental delays, free treatment for 30 health conditions"),
("pmay_clss", "PMAY Credit Linked Subsidy Scheme Home Loan Interest Subsidy\nCategory: Housing\nBenefit: Interest subsidy up to Rs 6.5 lakh on home loan for EWS LIG MIG families\nEligibility: EWS income up to Rs 3 lakh LIG Rs 3 to 6 lakh MIG Rs 6 to 18 lakh\nHow to Apply: Apply through bank or housing finance company\nDocuments: Aadhar card, income proof, property documents, bank account\nHelpline: 1800-116-446\nFeatures: Interest subsidy credited to loan account, reduces EMI significantly, first time home buyers only"),
("pm_jjby", "PM Jeevan Jyoti Bima Yojana Life Insurance Rs 2 Lakh Rs 436\nCategory: Insurance Financial\nBenefit: Rs 2 lakh life insurance cover at just Rs 436 per year\nEligibility: Bank account holders aged 18 to 50 years\nHow to Apply: Register through bank auto-debit from savings account\nDocuments: Aadhar card, bank account\nHelpline: 1800-180-1111\nFeatures: Cover Rs 2 lakh on death from any cause, premium only Rs 436 per year, no medical examination needed, annual renewal"),
("pm_sby", "PM Suraksha Bima Yojana Accident Insurance Rs 2 Lakh Rs 20\nCategory: Insurance Financial\nBenefit: Rs 2 lakh accident insurance at just Rs 20 per year\nEligibility: Bank account holders aged 18 to 70 years\nHow to Apply: Register through bank auto-debit from savings account\nDocuments: Aadhar card, bank account\nHelpline: 1800-180-1111\nFeatures: Rs 2 lakh for accidental death or permanent disability, Rs 1 lakh for partial disability, only Rs 20 per year"),
("stand_up_india", "Stand Up India SC ST Women Entrepreneur Loan Rs 10 Lakh to 1 Crore\nCategory: Business Financial\nBenefit: Bank loans from Rs 10 lakh to Rs 1 crore for SC ST and women entrepreneurs\nEligibility: SC ST and Women entrepreneurs above 18 years for new enterprises\nHow to Apply: Apply at bank branch or standupmitra.in\nDocuments: Aadhar card, business plan, caste certificate, property documents\nHelpline: 1800-11-0001\nFeatures: Composite loan term and working capital, margin money as low as 15 percent, repayment up to 7 years"),
("senior_citizen_savings", "Senior Citizen Savings Scheme SCSS 8.2 Percent Interest\nCategory: Financial Pension\nBenefit: 8.2 percent interest per year with quarterly payout for senior citizens\nEligibility: Citizens above 60 years retired defense personnel above 50\nHow to Apply: Post office or authorized banks\nDocuments: Age proof, Aadhar card, PAN card, retirement documents\nHelpline: 1800-11-2011\nFeatures: Maximum investment Rs 30 lakh, interest paid every quarter, 5 year tenure extendable by 3 years, tax benefit under 80C"),
("nsc", "National Savings Certificate NSC 7.7 Percent Safe Investment\nCategory: Financial Investment\nBenefit: 7.7 percent guaranteed return 5 year lock-in tax benefit under 80C\nEligibility: All Indian citizens\nHow to Apply: Post office\nDocuments: Aadhar card, PAN card\nHelpline: 1800-11-2011\nFeatures: Safe government-backed investment, minimum Rs 1000, can be pledged as collateral for bank loans, doubles money in 9.2 years"),
("beti_bachao", "Beti Bachao Beti Padhao Girl Child Education Save Daughter\nCategory: Women Child Education\nBenefit: Financial incentives and scholarships for girl child education and welfare\nEligibility: Girl children families with daughters\nHow to Apply: Contact Anganwadi center or school or district office\nDocuments: Birth certificate of girl child, Aadhar card\nHelpline: 1091\nFeatures: Addresses decline in child sex ratio, scholarships for girl students, awareness campaigns, prevention of female foeticide, empowerment through education"),
("mahila_shakti", "Mahila Shakti Kendra Women Empowerment Skill Training\nCategory: Women\nBenefit: Skill training digital literacy health and nutrition support for rural women\nEligibility: Women in rural areas\nHow to Apply: Visit nearest Mahila Shakti Kendra or district women cell\nDocuments: Aadhar card\nHelpline: 181\nFeatures: One-stop convergence of services, skill development training, legal aid and awareness, health and nutrition counseling, digital literacy training"),
("pmmvy", "Pradhan Mantri Matru Vandana Yojana Rs 6000 Maternity Benefit\nCategory: Women Health\nBenefit: Rs 6000 cash benefit for first live birth in 3 installments direct bank transfer\nEligibility: Pregnant and lactating women for first child aged 18 plus years\nHow to Apply: Register at Anganwadi center within 150 days of pregnancy\nDocuments: Aadhar card, bank account, MCP card, pregnancy registration\nHelpline: 1800-11-8004\nFeatures: Rs 3000 on early registration, Rs 2000 after first antenatal check, Rs 1000 after child birth, direct bank transfer"),
("one_stop_centre", "One Stop Centre Sakhi Women Safety Helpline 181 Free Help\nCategory: Women Safety\nBenefit: Free shelter medical legal and counseling help for women in distress 24x7\nEligibility: Women affected by violence or in any crisis situation\nHow to Apply: Call 181 Women Helpline or visit nearest Sakhi Center\nDocuments: No documents required for emergency help\nHelpline: 181 toll free 24x7\nFeatures: Emergency response 24x7, medical assistance, legal aid, counseling, police assistance, temporary shelter, available in all districts"),
("icds", "ICDS Anganwadi Integrated Child Development Free Nutrition\nCategory: Child Nutrition Health\nBenefit: Free nutrition health checkup pre-school education for children 0 to 6 years\nEligibility: Children 0 to 6 years pregnant women nursing mothers\nHow to Apply: Register at nearest Anganwadi center in your village\nDocuments: Birth certificate, Aadhar card\nHelpline: 1800-11-8004\nFeatures: Free nutritional food, immunization, health check-up, pre-school education, referral services, growth monitoring of children"),
("pm_evidya", "PM e-VIDYA Free Digital Education Online Learning DIKSHA\nCategory: Education Digital\nBenefit: Free digital education online classes study materials in all subjects\nEligibility: All students in India\nHow to Apply: Access through diksha.gov.in or TV channels Swayam app\nDocuments: None required\nHelpline: 1800-11-8004\nWebsite: diksha.gov.in\nFeatures: DIKSHA portal free content, Swayam online courses, one class one channel on DTH TV, available in regional languages"),
("mid_day_meal", "Mid Day Meal Scheme PM POSHAN Free Hot School Meals\nCategory: Education Nutrition\nBenefit: Free hot nutritious meal every school day for students in government schools\nEligibility: All students in Class 1 to 8 in government and government-aided schools\nHow to Apply: Automatic for enrolled students in government schools no application needed\nDocuments: School enrollment\nHelpline: 1800-11-8004\nFeatures: Free hot cooked meal every school day, improves attendance and retention, 11.20 crore children benefited"),
("nmms_scholarship", "National Means Merit Scholarship NMMS Rs 12000 Per Year Poor Students\nCategory: Education\nBenefit: Rs 12000 per year scholarship for class 9 to 12 students from poor families\nEligibility: Government school students family income below Rs 3.5 lakh score 55 percent in class 7\nHow to Apply: Through state education department exam conducted in November\nDocuments: Class 7 marksheet, income certificate, Aadhar card, bank account\nHelpline: 0120-6619540\nFeatures: Rs 1000 per month for 4 years, for low income students, state level exam, direct bank transfer"),
("kgbv", "Kasturba Gandhi Balika Vidyalaya Free Residential School Girls SC ST BPL\nCategory: Education Women\nBenefit: Free residential school for girl children from minority SC ST and BPL families\nEligibility: Girls from SC ST OBC minority and BPL families in educationally backward areas\nHow to Apply: Contact district education officer\nDocuments: Caste certificate, BPL card, birth certificate\nHelpline: 1800-11-2661\nFeatures: Free boarding and lodging, quality education Class 6 to 12, girls who dropped out can rejoin"),
("pmrpy", "PM Rozgar Protsahan Yojana EPF Government Contribution Employment\nCategory: Employment\nBenefit: Government pays 12 percent EPF contribution for 3 years for new employees\nEligibility: EPFO registered establishments hiring new workers earning below Rs 15000\nHow to Apply: Register on pmrpy.gov.in\nDocuments: EPFO registration, employee details\nHelpline: 1800-11-2811\nFeatures: Incentivizes employers to hire more workers, benefits workers getting formal employment"),
("ddugky", "DDU-GKY Rural Skill Training Free Job Placement 75 Percent Guarantee\nCategory: Employment Education\nBenefit: Free skill training and placement with Rs 1000 to 1500 stipend during training\nEligibility: Rural youth aged 15 to 35 years from poor families\nHow to Apply: Contact nearest DDU-GKY training center or district rural development office\nDocuments: Aadhar card, income certificate, caste certificate, bank account\nHelpline: 1800-11-0001\nFeatures: 75 percent placement guarantee, post placement support, training in 250 plus job roles"),
("pm_svanidhi", "PM SVANidhi Street Vendor Loan Rs 10000 to Rs 50000\nCategory: Employment Business\nBenefit: Working capital loan Rs 10000 first Rs 20000 second Rs 50000 third loan\nEligibility: Street vendors who were vending before March 24 2020\nHow to Apply: Apply through pmsvanidhi.mohua.gov.in or nearby urban local body\nDocuments: Vending certificate or letter of recommendation, Aadhar card, bank account\nHelpline: 1800-11-1979\nFeatures: Collateral free loan, 7 percent interest subsidy, digital transaction rewards, no processing fee"),
("nrlm", "National Rural Livelihood Mission NRLM Self Help Group Women Rs 6 Lakh Loan\nCategory: Employment Women\nBenefit: Self Help Group formation training Rs 15000 revolving fund and bank loan up to Rs 6 lakh\nEligibility: Rural poor families especially women\nHow to Apply: Contact Block Development Officer or local NRLM facilitator\nDocuments: Aadhar card, bank account, BPL card\nHelpline: 1800-11-0001\nFeatures: Form Self Help Group 10 to 15 women, Rs 15000 Community Investment Fund, training on livelihood, interest subvention on loans"),
("nfsa", "National Food Security Act PDS Ration Card Subsidized Grain\nCategory: Food\nBenefit: Rice at Rs 3 per kg Wheat at Rs 2 per kg Coarse grains at Rs 1 per kg\nEligibility: Priority households up to 75 percent rural and 50 percent urban population\nHow to Apply: Get ration card from local food department office\nDocuments: Aadhar card, residence proof, family details\nHelpline: 1967\nFeatures: 5 kg grain per person per month, heavily subsidized prices, available at fair price shops"),
("one_nation_ration", "One Nation One Ration Card Migrant Workers Use PDS Anywhere India\nCategory: Food\nBenefit: Use ration card at any fair price shop anywhere in India not just home state\nEligibility: All NFSA beneficiaries with Aadhar linked ration card\nHow to Apply: Link Aadhar to ration card at nearby CSC or ration shop\nDocuments: Ration card, Aadhar card\nHelpline: 1967\nFeatures: Migrant workers can use ration card anywhere in India, biometric verification at shop, Mera Ration app, active in all 36 states"),
("antyodaya", "Antyodaya Anna Yojana Poorest Families 35 kg Grain Yellow Card\nCategory: Food\nBenefit: 35 kg grain per month at Rs 2 to 3 per kg for poorest families more than normal PDS\nEligibility: Poorest of poor families destitute marginal farmers landless labourers widows disabled elderly\nHow to Apply: Contact local food and civil supplies office\nDocuments: BPL certificate, Aadhar card, residence proof\nHelpline: 1967\nFeatures: Yellow ration card special, 35 kg grain per month, priority to widows disabled elderly"),
("pm_ujala", "PM UJALA LED Bulb Scheme Cheap Energy Saving Rs 10 to 70\nCategory: Utility Energy\nBenefit: LED bulbs at Rs 10 to 70 instead of Rs 300 to 400 market price\nEligibility: All domestic electricity consumers with metered connections\nHow to Apply: Exchange old bulbs at nearest DISCOM office or distribution point\nDocuments: Electricity bill, Aadhar card\nHelpline: 1800-180-3333\nFeatures: 4 LED bulbs per household, energy saving fans also available, saves Rs 1000 to 2000 per year, reduces consumption by 75 percent"),
("saubhagya", "Saubhagya Scheme Free Electricity Connection Har Ghar Bijli\nCategory: Utility Energy\nBenefit: Free electricity connection to all unelectrified rural and urban poor households\nEligibility: Unelectrified households in rural and urban poor areas\nHow to Apply: Contact nearest electricity department or DISCOM office\nDocuments: Aadhar card, residence proof\nHelpline: 1800-166-6696\nFeatures: Free connection with LED bulb wire and switch, solar pack for remote areas, BPL families get free wiring also"),
("pm_kusum", "PM KUSUM Yojana Solar Pump 60 Percent Subsidy Farmers Irrigation\nCategory: Farmer Utility Energy\nBenefit: 60 percent subsidy on solar pumps for irrigation extra power can be sold to grid\nEligibility: Individual farmers groups of farmers Farmer Producer Organizations\nHow to Apply: Apply through state nodal agency for solar power\nDocuments: Aadhar card, land documents, bank account\nHelpline: 1800-180-3333\nFeatures: 60 percent subsidy 30 percent central 30 percent state, farmer pays only 10 percent, reduces diesel cost for irrigation"),
("jal_jeevan", "Jal Jeevan Mission Har Ghar Jal Free Tap Water Rural Household\nCategory: Utility Water\nBenefit: Free tap water connection to every rural household 55 liters per person per day\nEligibility: All rural households without tap water connection\nHow to Apply: Contact Gram Panchayat water committee\nDocuments: Aadhar card, residence proof\nHelpline: 1916\nWebsite: jaljeevanmission.gov.in\nFeatures: 55 liters per person per day, village water committee manages supply, water quality testing every 6 months"),
("pmgdisha", "PM Gramin Digital Saksharta Free Digital Literacy Training Rural\nCategory: Education Digital\nBenefit: Free digital literacy training computer internet UPI digital payments for rural people\nEligibility: Rural households with at least one member digitally illiterate\nHow to Apply: Register at nearest CSC or pmgdisha.in\nDocuments: Aadhar card\nHelpline: 1800-3000-3468\nFeatures: Free 20 hour training course, learn internet UPI mobile apps, certificate after training, available in local language"),
("bharatnet", "BharatNet Rural Broadband High Speed Internet Villages 100 Mbps\nCategory: Utility Digital\nBenefit: High speed broadband internet at affordable rates in rural areas 100 Mbps\nEligibility: All citizens in rural areas\nHow to Apply: Contact local service provider or CSC center\nDocuments: Aadhar card\nHelpline: 1800-425-1115\nFeatures: 100 Mbps broadband to all Gram Panchayats, affordable pricing, Wi-Fi hotspots in villages, enables telemedicine e-education online services"),
("aam_aadmi_bima", "Aam Aadmi Bima Yojana Insurance Landless Rural Households\nCategory: Insurance Financial\nBenefit: Rs 30000 natural death Rs 75000 accidental death Rs 37500 partial disability\nEligibility: Landless rural household heads aged 18 to 59 years\nHow to Apply: Contact LIC office or state nodal agency\nDocuments: Aadhar card, bank account, BPL card\nHelpline: 1800-33-4433\nFeatures: Rs 100 annual premium, government pays Rs 50, scholarship for children also, covers death and disability"),
("pm_vay_vandana", "PM Vaya Vandana Yojana Senior Citizen Pension 10 Years\nCategory: Financial Pension\nBenefit: Guaranteed 7.4 percent return for 10 years monthly quarterly yearly pension\nEligibility: Citizens above 60 years\nHow to Apply: LIC office or licindia.in\nDocuments: Age proof, Aadhar card, PAN card, bank account\nHelpline: 1800-33-4433\nFeatures: Maximum investment Rs 15 lakh, guaranteed pension for 10 years, loan facility after 3 years, return of purchase price on death"),
("dbt_direct_benefit", "Direct Benefit Transfer DBT All Subsidies Direct to Bank\nCategory: Financial\nBenefit: All government subsidies directly transferred to bank account no middlemen\nEligibility: All beneficiaries of government schemes with bank account and Aadhar\nHow to Apply: Link Aadhar to bank account at any bank branch\nDocuments: Aadhar card, bank account\nHelpline: 1800-11-0001\nFeatures: Eliminates middlemen, reduces leakage, faster transfer, covers fertilizer LPG scholarship food subsidy and more"),
("pm_fasal_bima_rabi", "Pradhan Mantri Fasal Bima Yojana Rabi Crop Insurance\nCategory: Farmer\nBenefit: Crop insurance coverage for rabi crops like wheat gram mustard at very low premium\nEligibility: All farmers including sharecroppers and tenant farmers growing notified crops\nHow to Apply: Through bank at time of crop loan or CSC center\nDocuments: Aadhar card, bank account, land records, sowing certificate\nHelpline: 1800-200-7710\nFeatures: Premium only 1.5 percent for rabi crops, covers natural calamities pests diseases, claim settled within 2 months"),
]

count = 0
for filename, content in schemes:
    filepath = f"data/{filename}.txt"
    if not os.path.exists(filepath):
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"Created: {filepath}")
        count += 1
    else:
        print(f"Exists: {filepath}")

total = len(os.listdir("data"))
print(f"\nNew files created: {count}")
print(f"Total files in data/: {total}")